#!/usr/bin/ruby
# frozen_string_literal: true

require 'pp'
require 'rubygems'
require 'openssl'
require 'aws-sdk-kms'
require 'base64'
require 'json'
require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = 'Usage: kms-encrypt.rb [options] INPUTFILE'

  opts.on('--output FILE', 'Write JSON output to FILE') do |f|
    options[:output] = f
  end

  opts.on('--device DEVICE', 'LUKS device path') do |d|
    options[:device] = d
  end
end.parse!

if ARGV[0].nil?
  puts 'Usage: kms-encrypt.rb --output FILE --device DEVICE INPUTFILE'
  exit 1
end

unless options[:output]
  puts 'Error: --output FILE is required'
  exit 1
end

unless options[:device]
  puts 'Error: --device DEVICE is required'
  exit 1
end

device = options[:device]

# Verify the device is a LUKS volume
unless system("cryptsetup --batch-mode isLuks #{device}")
  puts "Error: #{device} is not a LUKS volume (cryptsetup isLuks returned non-zero)"
  exit 1
end

# Get the device UUID via blkid
device_uuid = `blkid -s UUID -o value #{device}`.strip
if device_uuid.empty?
  puts "Error: Could not determine UUID for #{device}"
  exit 1
end

# This uses the envelope-encryption model.
# The cleartext is not sent to AWS KMS,
# rather an encryption key is generated by KMS
# and stored alongside the ciphertext.
# keyid looks like 6d83e627-bf08-1111-9999-23b0a0df19b1
keyid = ENV['KEYID']
plaintext = IO.read(ARGV[0])

kms = Aws::KMS::Client.new(region: 'us-east-1')

# Encryption_context can be thought of as part of the key;
# it must match on both the encrypt and decrypt end.
kmsresponse = kms.generate_data_key(
  key_id: keyid,
  encryption_context: { 'KeyType' => 'Some descriptive text here' },
  key_spec: 'AES_256'
)
alg = 'AES-256-CBC'
iv = OpenSSL::Cipher.new(alg).random_iv
aes = OpenSSL::Cipher.new(alg)
aes.encrypt
aes.key = kmsresponse['plaintext']
aes.iv = iv

cipher = aes.update(plaintext)
cipher << aes.final

cipher64 = Base64.strict_encode64(cipher)
outputhash = { 'device_uuid' => device_uuid,
               'ciphertext' => cipher64,
               'iv' => Base64.strict_encode64(iv),
               'datakey' => Base64.strict_encode64(
                 kmsresponse.ciphertext_blob
               ) }

File.write(options[:output], JSON.pretty_generate(outputhash))
