version: 2
orbs:
 # import CircleCI's aws-cli orb
 aws-cli: circleci/aws-cli@3.1

jobs:
   build:
     docker:
       - image: cimg/ruby:2.7.0
     steps:
       - checkout

       - aws-cli/setup:
           role-arn: 'arn:aws:iam::186675908400:role/circleci-kms'
           aws-region: "us-west-2"
           # optional parameters
           role-session-name: "CircleCI"
           session-duration: 90

       # Restore bundle cache
       - type: cache-restore
         key: bundle-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
       - run: bundle install --path vendor/bundle

       # Store bundle cache
       - type: cache-save
         key: bundle-{{ checksum "Gemfile.lock" }}
         paths:
           - vendor/bundle

       - run: bash -x ./test.sh
