version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.1.1
jobs:
   build:
     environment:
       AWS_REGION: us-east-1
     docker:
       - image: cimg/ruby:3.4.6
     steps:
       - checkout

       - aws-cli/setup:
          profile_name: OIDC-PROFILE
          role_arn: arn:aws:iam::186675908400:role/circleci-kms
          role_session_name: CircleCI

#        # Restore bundle cache
#       - restore_cache:
#           key: bundle-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
       - run:
           name: Bundler
           command: bundle install --path vendor/bundle

       # Store bundle cache
       - save_cache:
           name: Save bundles
           key: bundle-{{ checksum "Gemfile.lock" }}
           paths:
             - vendor/bundle

       - run:
           name: Run Test
           command: bash -x ./test.sh
           environment:
             AWS_PROFILE: OIDC-PROFILE

workflows:
  aws-cli:
    jobs:
      - build:
          context: aws
