version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.5
jobs:
   build:
     environment:
       AWS_PROFILE: "OIDC-PROFILE"
       AWS_REGION: us-west-2
     docker:
       - image: cimg/ruby:2.7.0
     steps:
       - checkout
       - aws-cli/setup:
          role-arn: "arn:aws:iam::186675908400:role/circleci-kms"
          aws-region: AWS_REGION
          # optional parameters
          profile-name: "OIDC-PROFILE"
          role-session-name: "CircleCI"
          session-duration: "1800"

       # Restore bundle cache
       - restore_cache:
           key: bundle-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
       - run:
           name: Bundler
           command: bundle install --path vendor/bundle

       # Store bundle cache
       - save_cache:
           name: Save bundles
           key: bundle-{{ checksum "Gemfile.lock" }}
           paths:
             - vendor/bundle

       - run:
           name: Run Test
           command: bash -x ./test.sh
